name: Manual Migration Trigger

on:
  workflow_dispatch:

jobs:
  run-migration:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Azure DevOps Migration Tools
        run: |
          Invoke-WebRequest -Uri "https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/v16.16.20/MigrationTools.ConsoleApp.16.16.20.zip" -OutFile "migration.zip"
          Expand-Archive -Path "migration.zip" -DestinationPath "migration-tools"
        shell: pwsh

      - name: Replace secrets in configuration file
        run: |
          $template = Get-Content configuration.template.json -Raw
          $template = $template -replace '__SOURCE_PAT__', "${{ secrets.SOURCE_PAT }}"
          $template = $template -replace '__TARGET_PAT__', "${{ secrets.DESTINATION_PAT }}"
          Set-Content -Path configuration.json -Value $template
        shell: pwsh

      - name: Run Migration Tool
        run: |
          cd migration-tools
          ./MigrationTools.Console.exe execute -c ../configuration.json
        shell: pwsh
